const mongoose = require('mongoose');

// Conversation Schema - Stores chat history between user and AI
const ConversationSchema = new mongoose.Schema({
  // User Reference
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true,
  },
  
  // Session Information
  sessionId: {
    type: String,
    required: true,
    unique: true,
    index: true,
  },
  
  title: {
    type: String,
    default: 'New Conversation',
    trim: true,
  },
  
  // Messages Array
  messages: [{
    role: {
      type: String,
      enum: ['user', 'assistant', 'system'],
      required: true,
    },
    content: {
      type: String,
      required: true,
      trim: true,
    },
    timestamp: {
      type: Date,
      default: Date.now,
    },
    
    // Additional metadata for AI responses
    metadata: {
      // Which AI agent responded
      agent: {
        type: String,
        enum: ['symptom-analyzer', 'risk-assessor', 'doctor-finder', 'general'],
      },
      
      // Related symptom analysis (if any)
      symptomAnalysisId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'SymptomAnalysis',
      },
      
      // Sources used for RAG
      sources: [{
        type: String,
        ref: 'MedicalResource',
      }],
      
      // Confidence score (0 to 1)
      confidence: {
        type: Number,
        min: 0,
        max: 1,
      },
    },
  }],
  
  // Conversation Context
  context: {
    // Current symptoms being discussed
    currentSymptoms: [String],
    
    // Previous analyses in this conversation
    previousAnalyses: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'SymptomAnalysis',
    }],
    
    // User preferences for responses
    userPreferences: {
      detailLevel: {
        type: String,
        enum: ['simple', 'detailed', 'technical'],
        default: 'detailed',
      },
      includeSources: {
        type: Boolean,
        default: true,
      },
    },
  },
  
  // Conversation Summary (generated by AI)
  summary: String,
  
  // Status
  isActive: {
    type: Boolean,
    default: true,
    index: true,
  },
  
  endedAt: Date,
  
  // Timestamps
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
});

module.exports = mongoose.model('Conversation', ConversationSchema);